# -*- coding: utf-8 -*-
"""Michelle_NER_RE_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1axpTunJBlokkv9q8lu4eG3cn_UfQfkI8
"""

import spacy
from transformers import pipeline
import torch

Sample_501K_File = "K060065-Reply to FDA Letter of March 2, 2006 Confidential"
"10.1.3.2. 510(k) Summary of Safety and Effectiveness"
"Information Capnostream 20and Capnostream"
"51 0(k) Summary of Safety and Effectiveness Information"
"Capnostream 20 and Capnostream10"
"(This document is not conrtidential)"

"DATE THIS SUMMARY WAS PREPARED"

"March 20, 2006"

"SUBMITTERS NAME AND ESTABLISHMENT ADDRESS:"

"Oridion Capnography Inc."
"21 Highland Circle"
"Needham, MA 02494-3038"

"PRODUCT NAMES"
"NOTE: This summary statement is for a bundled submission and covers the Capnostreamn2o"
"and Capnostreaml 0"
"CapnostroaM 20"
"Proprietary: Capnostream 20"
"Common: Two Parameter Bedside Monitor"
"Capnostrearn10"
"Proprietary: Capnostream10"
"Common: One Parameter Bedside Monitor"
"ESTABLISHMENT REGISTRATION NUMBER"
"Establishment Registration Number: 3003941644"
"CONTACT PERSON:"
"Sanford Brown, Regulatory Affairs Director"
"Oridion Medical 1987 Ltd."
"Har Hotzvim Science Based Industrial Park"
"P06 45025"
"91450 Jerusalem, Israel"
"Telephone: +972-2-589-9115"
"FAX: +972-2-586-6680"

"Oridion Medical 1987 Ltd. Page 76"

"K060065-Reply to FDA Letter of March 2, 2006 Confidential"
"DEVICE LISTING FDA FORM 2892:"

"B051971"

"DEVICE DESCRIPTIONS"
"%*° Capnostream 20"
"The Capnostream 20 bedside monitor is a two parameter monitor consisting of an EtCO 2"
"MiniMediCO 2 module and a MP100 SpO 2 module, displays and alarms."
"SUBSTANTIAL EQUIVALENCE INFORMATION"
"* CO2 Module (MiniMediCO 2) used in legally marketed Predicate Devices:"

"V Oridion Polaris 2004, K04001 1,"
"V CAS Medical Systems, Inc Models 750c-2ms, 750cm-2ms,"
"750c-Nnl, 750cm with MiniMediCO 2-V1 K050844"
"V Larsen & Toubro Limited Star 50 Monitoring System K051608"

"* Pulse Oximeter Module, Sp02 Module (MP100) used in legally marketed Predicate"
"Devices:"
", NPB OxiMax Pulse Oximeter System With N-595 Pulse"
"Oximeter, K012891"
"v NPB Oximax N-550, K021090"

"* Nurse Call"

"v NPB OxiMax Pulse Oximeter System With N-595 Pulse"
"Oximeter, K012891"
"· Welch Allyn Atlas Monitor K022084"

"CLASSIFICATION"
"Capnostream 20"
"73CCK Class [I]"
"This device has two modules that are classified as follows:"
"* 21 CFR 868.1400, carbon dioxide analyzer"
"* 21 CFR870.2700 Pulse Oximeter"
"INTENDED USE"
"The Capnostream20 is intended for CO2 and SP02 indications. The Capnostream2 0"
"combined capnograph/pulse oximeter monitor is intended to provide professionally trained"
"health care providers the continuous, non invasive measurement and monitoring of carbon"
"dioxide concentration of the expired and inspired breath and respiration rate, and for the"
"continuous non-invasive monitoring of functional oxygen saturation of arterial hemoglobin"
"(SpO2 and pulse rate). It is intended for use with neonatal, pediatric and adult patients in"
"hospitals, hospital type facilities, intra hospital moves and home environments."
"Oridion Medical 1987 Ltd. Page 77"

"K060065-Reply to FDA Letter of March 2, 2006 Confidential"
"DEVICE DESCRIPTION"
"The Capnostream20 Bedside Monitor is comprised of two modules used in previously FDA"
"cleared devices with the following indications for use, which together are the indications for"
"use for the two parameter bedside monitor:"
"Capnostream 20"
"1. The MiniMediCO2 EtCO2 Module:"
"Is intended for installation in host devices that: are used by physicians, nurses and other"
"trained health care providers in critical care patient settings, such as anesthesiology, intensive care medicine, neonatal Intensive care and other health care areas where non"
"invasive measurement of expired C02 and inspired C02 are of medical value. It"
"continuously and non invasively measures and monitors carbon dioxide concentration of the"
"expired and inspired breath and respiration rate. This module is designed to be installed in a"
"host device, in this case the two Parameter Bedside Monitor, that is for prescription use"
"only."

"2. The MP100 Oximetry Module"
"Is indicated for the continuous non-invasive monitoring of functional oxygen saturation of arterial hemoglobin (SpO2) and pulse rate. It is intended for use with neonatal, pediatric, and adult patients during both no motion and motion conditions and for patients who are"
"either well or poorly perfused. It is to be used by physicians, nurses and other trained health"
"care providers in critical care patient settings, such as anesthesiology, intensive care"
"medicine, neonatal Intensive care and other health care areas. This module is designed to"
"be installed in a host device, in this case the two Parameter Bedside Monitor, that is for"
"prescription use only.."
"-*. Capnostreami0"
"Capnostream1 0"
"Proprietary: Capnostream1 0"
"Common: One Parameter Bedside Monitor"

"ESTABLISHMENT REGISTRATION NUMBER"
"Establishment Registration Number: 3003941644"

"CONTACT PERSON:"
"Sanford Brown, Regulatory Affairs Director"
"Oridion Medical 1987 Ltd."
"Har Hotzvim Science Based Industrial Park"
"POB 45025"
"91450 Jerusalem, Israel"
"Oridion Medical 1987 Ltd. Page 78"

"K060065-Reply to FDA Letter of March 2, 2006 Confidential"
"Telephone: +972-2-589-9115"
"FAX: +972-2-586-6680"

"DEVICE LISTING FDA FORM 2892:"

"B051971"
"DEVICE DESCRIPTION"
"The Capnostreamlo bedside monitor is a one parameter monitor consisting of a MP100"
"EtCO2 module displays and alarms."

"SUBSTANTIAL EQUIVALENCE INFORMATION"
"* CO2 Module (MiniMediCO 2) used in Predicate Devices:"

"' Oridion Polaris 2004, K04001 1,"
"/ CAS Medical Systems, Inc Models 750c-2ms, 750cm-2ms,"
"750c-Nnl, 750cm with MiniMediC0 2-V1 K050844"
"v Larsen & Toubro Limited Star 50 Monitoring System K051608"

"CLASSIFICATION"
"Capnostreaml 0"
"73CCK Class [I"
"This device is classified as follows:"
"* 21 CFR 868.1400, carbon dioxide analyzer"
"INTENDED USE"
"The Capnostream10 is intended for C02 indications only. The Capnostream10 is intended to"
"provide professionally trained health care providers the continuous, non invasive"
"measurement and monitoring of carbon dioxide concentration of the expired and inspired"
"breath. It is intended for use with neonatal, pediatric and adult patients in hospitals, hospital"
"type facilities, intra hospital moves and home environments."

"Oridion Medical 1987 Ltd. Page 79"

"K060065-Reply to FDA Letter of March 2, 2006 Confidential"
"DEVICE DESCRIPTION"
"The Capnostream10 Bedside Monitor contains a MinMediCO 2 EtCO 2 module used in"
"previously FDA cleared devices with the following indications for use."
"The MiniMediCO 2 EtCO 2 Module:"
"Is intended for installation in host devices that: are used by physicians, nurses and other"
"trained health care providers in critical care patient settings, such as anesthesiology, intensive care medicine, neonatal Intensive care and other health care areas where non"
"invasive measurement of expired CO2 and inspired CO2 are of medical value. It"
"continuously and non invasively measure and monitor carbon dioxide concentration of the"
"expired and inspired breath and respiration rate."
"This module is designed to be installed in a host device, in this case the one Parameter"
"Bedside Monitor, that is for prescription use only."

import spacy
from transformers import pipeline
import torch
from spacy.language import Language

@Language.factory("rebel")
def create_rebel_component(nlp, name, device, model_name):
    return pipeline("text2text-generation", model=model_name, device=device)

#load the model
nlp = spacy.load("en_core_web_sm")

nlp.add_pipe("rebel", after="senter", config={
    'device':-1, # Number of the GPU, -1 if want to use CPU
    'model_name':'Babelscape/rebel-large'} # Model used, will default to 'Babelscape/rebel-large' if not given
    )

doc = nlp(Sample_501K_File)
doc_list = nlp.pipe([Sample_501K_File])
for value, rel_dict in doc._.rel.items():
    print(f"{value}: {rel_dict}")

"""Begin prompting gemini to build a knowledge graph with and without ontology"""